name: Next.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Lint
        run: pnpm run lint

      - name: Build Next.js app
        run: pnpm run build

      - name: Build Next.js app
        run: pnpm run deploy
